views/intent_views.py
from flask import Blueprint, request, render_template
from form import IntentMessageForm
from models import get_intent_paging, get_intent_data_list, post_intent
from utils import request_get

bp = Blueprint('intent', __name__, url_prefix='/intent')

@bp.route('/', methods=('GET', 'POST'))
def _list():
    form = IntentMessageForm()
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    if request.method == 'POST' and form.validate_on_submit():
        intent = form.intent.data
        request_data = {'intent':intent}
        post_intent(request_data)
    paging, data_list, data_len = get_intent_paging(page=page, sort=so_list, keyword=keyword)
    # data_len = data_list.count()
    return render_template('intent/intent_list.html', **locals())

@bp.route('/<intent>/', methods=('GET', 'POST'))
def intent_detail(intent):
    form = IntentMessageForm()
    page, keyword, so, so_list = request_get(request.args)
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'msg':form.msg.data, 'intent':form.intent.data}
        post_intent(request_data)
    paging, data_list = get_intent_data_list(intent, page=page, keyword=keyword)
    return render_template('intent/intent_detail.html', **locals())

views/monitoring_views.py
from flask import Blueprint, request, render_template, url_for, g, flash
from werkzeug.utils import redirect
from form import MonitoringForm
from models import get_category_list, get_monitoring_data_list, post_monitoring, get_nlp_list, get_nlp_wrong_list, get_accuracy_list, get_statistics_list
from utils import request_get
import functools

category_list = get_category_list()

# blueprint
bp = Blueprint('monitoring', __name__, url_prefix='/monitoring')

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('main.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/', methods=('GET', 'POST'))
def monitoring():
    form = MonitoringForm()
    sort_type = 'timestamp'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    if request.method == 'POST' and form.validate_on_submit():
        category = form.category.data
        if category not in category_list and category != 'unknown':
            flash('there is no that kind of category')
        else:
            post_monitoring(timestamp=form.timestamp.data, category=category)
    paging, data_list = get_monitoring_data_list(page=page, sort=so_list, keyword=keyword)
    return render_template('monitoring/monitoring.html', **locals())

@bp.route('/nlp/')
def nlp():
    page, keyword, so, so_list = request_get(request.args)
    paging, data_list = get_nlp_list(page=page, keyword=keyword)
    return render_template('monitoring/nlp.html', **locals())

@bp.route('/wrong_prediction/')
def wrong_prediction():
    page, keyword, so, so_list = request_get(request.args)
    paging, data_list = get_nlp_wrong_list(page=page, keyword=keyword)
    return render_template('monitoring/wrong_prediction.html', **locals())

@bp.route('/accuracy/')
@login_required
def accuracy():
    sort_type = 'date'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, collection_list = get_accuracy_list(page=page, sort=so_list)
    data_list = []
    xlabels = []
    deep_dataset1 = []
    deep_dataset2 = []
    deep_dataset3 = []
    bay_dataset1 = []
    bay_dataset2 = []
    bay_dataset3 = []
    for data in collection_list:
        data_list.append(data)
        xlabels.append(data['date'])
        deep_dataset1.append(data['deep_accuracy'][0])
        deep_dataset2.append(data['deep_accuracy'][1])
        deep_dataset3.append(data['deep_accuracy'][2])
        bay_dataset1.append(data['bay_accuracy'][0])
        bay_dataset2.append(data['bay_accuracy'][1])
        bay_dataset3.append(data['bay_accuracy'][2])
    xlabels.reverse()
    deep_dataset1.reverse()
    deep_dataset2.reverse()
    deep_dataset3.reverse()
    bay_dataset1.reverse()
    bay_dataset2.reverse()
    bay_dataset3.reverse()

    sort_type = 'timestamp'
    return render_template('monitoring/accuracy.html', **locals())

@bp.route('/statistics/')
@login_required
def statistics():
    sort_type = 'date'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    accuracy_list, word_list = get_statistics_list()
    xlabels = []
    deep_dataset1 = []
    deep_dataset2 = []
    deep_dataset3 = []
    bay_dataset1 = []
    bay_dataset2 = []
    bay_dataset3 = []
    for data in accuracy_list:
        xlabels.append(data['date'])
        deep_dataset1.append(data['deep_accuracy'][0])
        deep_dataset2.append(data['deep_accuracy'][1])
        deep_dataset3.append(data['deep_accuracy'][2])
        bay_dataset1.append(data['bay_accuracy'][0])
        bay_dataset2.append(data['bay_accuracy'][1])
        bay_dataset3.append(data['bay_accuracy'][2])

    word_set = []
    count_set = []
    for data in word_list:
        word_set.append(data['word'])
        count_set.append(data['count'])
    return render_template('monitoring/statistics.html', **locals())

# render_template with multiple variables
# **locals() : https://stackoverflow.com/questions/12096522/render-template-with-multiple-variables

views/word_views.py
from flask import Blueprint, request, render_template, url_for
from werkzeug.utils import redirect
from form import PrewordForm
from models import get_word_list, get_typo_synonym, post_pre_word, get_pre_words
from utils import request_get

bp = Blueprint('word', __name__, url_prefix='/word')
typo_synonym = get_typo_synonym()

@bp.route('/')
def word():
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, data_list = get_word_list(page=page, sort=so_list, keyword=keyword)
    return render_template('word/word.html', typo_synonym=typo_synonym, **locals())

@bp.route('/<word>/', methods=('GET', 'POST'))
def pre_word(word):
    form = PrewordForm()
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'type':form.type.data, 'word':word, 'sub':form.sub.data}
        post_pre_word(request_data)
        global typo_synonym
        typo_synonym = get_typo_synonym()
        return redirect(url_for('word.word'))
    return render_template('word/pre_word.html', **locals())

@bp.route('/pre_words/')
def pre_words():
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, data_list, keyword, useless_word_count = get_pre_words(page=page, sort=so_list, keyword=keyword)
    return render_template('word/pre_words.html', **locals())

templates/intent/intent_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h1>{{ intent }}</h1>
    {% if g.user %}
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="form-group">
            <input type="hidden" class="form-control" name="intent" value="{{ intent }}">
            <label for="msg">message</label>
            <input type="text" class="form-control" name="msg" id="msg">
        </div>
        <button type="submit" class="btn btn-primary">등록</button>
    </form>
    {% endif %}
    {% include 'search.html' %}
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>message</th>
            {% if g.user %}
            <th>intent</th>
            <th>수정</th>
            {% endif %}
            <th>timestamp</th>
        </tr>
        </thead>
        {% if data_list %}
        {% for intent in data_list %}
        <tr>
            <td>{{ paging.count - paging.offset - loop.index0 }}</td>
            <td>{{ intent.msg }}</td>
            {% if g.user %}
            <form method="post" class="my-3">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <input type="hidden" name="msg" value="{{ intent.msg }}">
                <td><input type="text" class="form-control" name="intent" value="{{ intent.intent }}" size="10"></td>
                <td><input type="submit" class="btn btn-primary"></td>
            </form>
            {% endif %}
            <td>{{ intent.timestamp }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">의도가 없습니다.</td>
        </tr>
        {% endif %}
    </table>
</div>

{% include 'paging.html' %}
{% endblock %}

templates/intent/intent_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    {% if g.user and data_len !=1 %}
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="intent">intent</label>
            <input type="text" class="form-control" name="intent" id="intent" value="{{ intent }}">
            <input type="hidden" class="form-control" name="msg" id="msg" value="msg">
        </div>
        <button type="submit" class="btn btn-primary">등록</button>
    </form>
    {% endif %}
    {% include 'search.html' %}
<table class="table">
    {% if data_list %}
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>intent</th>
            <th>count</th>
            <th>timestamp</th>
        </tr>
        </thead>
        {% for intent in data_list %}
        <tr>
            <td>{{ paging.count - paging.offset - loop.index0 }}</td>
            <td><a href="{{ url_for('intent.intent_detail', intent=intent.intent) }}">{{ intent.intent }}</a></td>
            <td>{{ intent.count }}</td>
            <td>{{ intent.timestamp }}</td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">의도가 없습니다.</td>
        </tr>
{% endif %}
</table>
</div>

{% include 'paging.html' %}
{% endblock %}

templates/intent/word.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">

    {% include 'search.html' %}

<table class="table">
    {% if data_list %}
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>word</th>
            <th>count</th>
        </tr>
        {% for intent in data_list %}
        <tr>
            <td>{{ paging.count - paging.offset - loop.index0 }}</td>
            <td><a href="{{ url_for('intent.nlp', kw=intent.word) }}">{{ intent.word }}</a></td>
            <td>{{ intent.count }}</td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">there is no word.</td>
        </tr>
{% endif %}
</table>
</div>

{% include 'paging.html' %}
{% endblock %}