views/word_views.py
from flask import Blueprint, request, render_template, url_for
from werkzeug.utils import redirect
from form import PrewordForm
from models import get_word_list, get_typo_synonym, post_pre_word, get_pre_words
from utils import request_get

bp = Blueprint('word', __name__, url_prefix='/word')
typo_synonym = get_typo_synonym()

@bp.route('/')
def word():
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, data_list = get_word_list(page=page, sort=so_list, keyword=keyword)
    return render_template('word/word.html', typo_synonym=typo_synonym, **locals())

@bp.route('/<word>/', methods=('GET', 'POST'))
def pre_word(word):
    form = PrewordForm()
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'type':form.type.data, 'word':word, 'sub':form.sub.data}
        post_pre_word(request_data)
        global typo_synonym
        typo_synonym = get_typo_synonym()
        return redirect(url_for('word.word'))
    return render_template('word/pre_word.html', **locals())

@bp.route('/pre_words/')
def pre_words():
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, data_list, keyword, useless_word_count = get_pre_words(page=page, sort=so_list, keyword=keyword)
    return render_template('word/pre_words.html', **locals())

templates/word/pre_word.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
<table class="table">
    {% if word %}
        <thead>
        <tr class="thead-dark">
            <th>word</th>
            <th>type</th>
            <th>sub</th>
            <th>확인</th>
        </tr>
        </thead>
        <tr>
            <form method="post" class="my-3">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <td>{{ word }}</td>
                <td>
                    typo <input type="radio" name="type" value="typo" checked />
                    synonym <input type="radio" name="type" value="synonym" />
                    stopwords <input type="radio" name="type" value="stopwords" />
                    split <input type="radio" name="type" value="split" />
                    custom_vocab <input type="radio" name="type" value="custom_vocab" />
                </td>
                <td><input type="text" class="form-control" name="sub" value="" size="10"></td>
                <td><input type="submit" class="btn btn-primary"></td>
            </form>
        </tr>
    {% else %}
        <tr>
            <td colspan="3">there is no word.</td>
        </tr>
{% endif %}
</table>
</div>
{% endblock %}

templates/word/pre_words.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">

    {% include 'search.html' %}
    <h1>type: {{ keyword }} , useless_word_count: {{ useless_word_count }}</h1>

<table class="table">
    {% if data_list %}
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>word</th>
            <th>count</th>
        </tr>
        </thead>
        {% for intent in data_list %}
        <tr>
            <td>{{ paging.count - paging.offset - loop.index0 }}</td>
            <td>{{ intent.word }}</td>
            <td>{{ intent.count }}</td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">there is no word.</td>
        </tr>
{% endif %}
</table>
</div>

{% include 'paging.html' %}
{% endblock %}

templates/word/word.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">

    {% include 'search.html' %}

<table class="table">
    {% if data_list %}
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>word</th>
            <th>synonym</th>
            <th>count</th>
        </tr>
        </thead>
        {% for intent in data_list %}
        <tr>
            <td>{{ paging.count - paging.offset - loop.index0 }}</td>
            <td><a href="{{ url_for('word.pre_word', word=intent.word) }}">{{ intent.word }}</a></td>
            <td>{{ typo_synonym[intent.word] }}</td>
            <td>{{ intent.count }}</td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="3">there is no word.</td>
        </tr>
{% endif %}
</table>
</div>

{% include 'paging.html' %}
{% endblock %}