views/intent_views.py
from flask import Blueprint, request, render_template
from form import IntentMessageForm
from models import get_intent_paging, get_intent_data_list, post_intent
from utils import request_get

bp = Blueprint('intent', __name__, url_prefix='/intent')

@bp.route('/', methods=('GET', 'POST'))
def _list():
    form = IntentMessageForm()
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    if request.method == 'POST' and form.validate_on_submit():
        intent = form.intent.data
        request_data = {'intent':intent}
        post_intent(request_data)
    paging, data_list, data_len = get_intent_paging(page=page, sort=so_list, keyword=keyword)
    # data_len = data_list.count()
    return render_template('intent/intent_list.html', **locals())

@bp.route('/<intent>/', methods=('GET', 'POST'))
def intent_detail(intent):
    form = IntentMessageForm()
    page, keyword, so, so_list = request_get(request.args)
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'msg':form.msg.data, 'intent':form.intent.data}
        post_intent(request_data)
    paging, data_list = get_intent_data_list(intent, page=page, keyword=keyword)
    return render_template('intent/intent_detail.html', **locals())

views/main_views.py
from flask import Blueprint, request, render_template, url_for, session, g, flash
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect
import functools

from form import UserCreateForm, UserLoginForm
from models import post_sign_up, post_login

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('main.login'))
        return view(**kwargs)
    return wrapped_view

# blueprint
bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return redirect(url_for('monitoring.monitoring'))

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'name':form.name.data, 'email':form.email.data, 'password':generate_password_hash(form.password1.data)}
        error = post_sign_up(request_data)
        if error:
            flash('이미 존재하는 사용자입니다.')
        else:
            return redirect(url_for('main.index'))
    return render_template('account/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'email':form.email.data, 'password':form.password.data}
        error, user_data = post_login(request_data)
        if error is None:
            del user_data['_id']
            del user_data['password']

            session.clear()
            for key in user_data:
                session[key] = user_data[key]
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('account/login.html', form=form)

@bp.route('/logout/')
@login_required
def logout():
    session.clear()
    return redirect(url_for('main.index'))

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = {}
        for key in session:
            g.user[key] = session[key]

views/monitoring_views.py
from flask import Blueprint, request, render_template, url_for, g, flash
from werkzeug.utils import redirect
from form import MonitoringForm
from models import get_category_list, get_monitoring_data_list, post_monitoring, get_nlp_list, get_nlp_wrong_list, get_accuracy_list, get_statistics_list
from utils import request_get
import functools

category_list = get_category_list()

# blueprint
bp = Blueprint('monitoring', __name__, url_prefix='/monitoring')

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('main.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/', methods=('GET', 'POST'))
def monitoring():
    form = MonitoringForm()
    sort_type = 'timestamp'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    if request.method == 'POST' and form.validate_on_submit():
        category = form.category.data
        if category not in category_list and category != 'unknown':
            flash('there is no that kind of category')
        else:
            post_monitoring(timestamp=form.timestamp.data, category=category)
    paging, data_list = get_monitoring_data_list(page=page, sort=so_list, keyword=keyword)
    return render_template('monitoring/monitoring.html', **locals())

@bp.route('/nlp/')
def nlp():
    page, keyword, so, so_list = request_get(request.args)
    paging, data_list = get_nlp_list(page=page, keyword=keyword)
    return render_template('monitoring/nlp.html', **locals())

@bp.route('/wrong_prediction/')
def wrong_prediction():
    page, keyword, so, so_list = request_get(request.args)
    paging, data_list = get_nlp_wrong_list(page=page, keyword=keyword)
    return render_template('monitoring/wrong_prediction.html', **locals())

@bp.route('/accuracy/')
@login_required
def accuracy():
    sort_type = 'date'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, collection_list = get_accuracy_list(page=page, sort=so_list)
    data_list = []
    xlabels = []
    deep_dataset1 = []
    deep_dataset2 = []
    deep_dataset3 = []
    bay_dataset1 = []
    bay_dataset2 = []
    bay_dataset3 = []
    for data in collection_list:
        data_list.append(data)
        xlabels.append(data['date'])
        deep_dataset1.append(data['deep_accuracy'][0])
        deep_dataset2.append(data['deep_accuracy'][1])
        deep_dataset3.append(data['deep_accuracy'][2])
        bay_dataset1.append(data['bay_accuracy'][0])
        bay_dataset2.append(data['bay_accuracy'][1])
        bay_dataset3.append(data['bay_accuracy'][2])
    xlabels.reverse()
    deep_dataset1.reverse()
    deep_dataset2.reverse()
    deep_dataset3.reverse()
    bay_dataset1.reverse()
    bay_dataset2.reverse()
    bay_dataset3.reverse()

    sort_type = 'timestamp'
    return render_template('monitoring/accuracy.html', **locals())

@bp.route('/statistics/')
@login_required
def statistics():
    sort_type = 'date'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    accuracy_list, word_list = get_statistics_list()
    xlabels = []
    deep_dataset1 = []
    deep_dataset2 = []
    deep_dataset3 = []
    bay_dataset1 = []
    bay_dataset2 = []
    bay_dataset3 = []
    for data in accuracy_list:
        xlabels.append(data['date'])
        deep_dataset1.append(data['deep_accuracy'][0])
        deep_dataset2.append(data['deep_accuracy'][1])
        deep_dataset3.append(data['deep_accuracy'][2])
        bay_dataset1.append(data['bay_accuracy'][0])
        bay_dataset2.append(data['bay_accuracy'][1])
        bay_dataset3.append(data['bay_accuracy'][2])

    word_set = []
    count_set = []
    for data in word_list:
        word_set.append(data['word'])
        count_set.append(data['count'])
    return render_template('monitoring/statistics.html', **locals())

# render_template with multiple variables
# **locals() : https://stackoverflow.com/questions/12096522/render-template-with-multiple-variables

views/word_views.py
from flask import Blueprint, request, render_template, url_for
from werkzeug.utils import redirect
from form import PrewordForm
from models import get_word_list, get_typo_synonym, post_pre_word, get_pre_words
from utils import request_get

bp = Blueprint('word', __name__, url_prefix='/word')
typo_synonym = get_typo_synonym()

@bp.route('/')
def word():
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, data_list = get_word_list(page=page, sort=so_list, keyword=keyword)
    return render_template('word/word.html', typo_synonym=typo_synonym, **locals())

@bp.route('/<word>/', methods=('GET', 'POST'))
def pre_word(word):
    form = PrewordForm()
    if request.method == 'POST' and form.validate_on_submit():
        request_data = {'type':form.type.data, 'word':word, 'sub':form.sub.data}
        post_pre_word(request_data)
        global typo_synonym
        typo_synonym = get_typo_synonym()
        return redirect(url_for('word.word'))
    return render_template('word/pre_word.html', **locals())

@bp.route('/pre_words/')
def pre_words():
    sort_type = 'count'
    page, keyword, so, so_list = request_get(request.args, sort_type=sort_type)
    paging, data_list, keyword, useless_word_count = get_pre_words(page=page, sort=so_list, keyword=keyword)
    return render_template('word/pre_words.html', **locals())

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>chatbot</title>
    <meta charset="utf-8">
    <!-- jQuery JS -->
    <script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
    </style>
</head>
<body>
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
<!-- ------------------------------ [edit] -------------------------------- -->
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
<!-- ---------------------------------------------------------------------- -->

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">chatbot</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.logout') }}">{{ g.user.name }} (로그아웃)</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('intent._list') }}">intent</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.monitoring') }}">monitoring</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.nlp') }}">nlp</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.wrong_prediction') }}">wrong_prediction</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('word.word') }}">word</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('word.pre_words') }}">pre_words</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.accuracy') }}">accuracy</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.statistics') }}">statistics</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.signup') }}">계정생성</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.login') }}">로그인</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('intent._list') }}">intent</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.monitoring') }}">monitoring</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.nlp') }}">nlp</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('monitoring.wrong_prediction') }}">wrong_prediction</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('word.word') }}">word</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

templates/paging.html
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if paging.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?kw={{ keyword or '' }}&page=1&so={{ so or '' }}">처음</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="?kw={{ keyword or '' }}&page={{ paging.prev_num }}&so={{ so or '' }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in paging.pages %}
        {% if page_num %}
            {% if page_num != paging.page %}
            <li class="page-item">
                <a class="page-link" href="?kw={{ keyword or '' }}&page={{ page_num }}&so={{ so or '' }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
            </li>
            {% endif %}
        {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if paging.has_next %}
    <li class="page-item">
        <a class="page-link" href="?kw={{ keyword or '' }}&page={{ paging.next_num }}&so={{ so or '' }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>

templates/search.html
<div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
    <div class="col-2">
        <select class="form-control so">
            {% if sort_type=='timestamp' %}
                <option value="recent" {% if so=='recent' %}selected{% endif %}>최신순</option>
                <option value="old" {% if so=='old' %}selected{% endif %}>오래된순</option>
            {% elif sort_type=='count' %}
                <option value="popular" {% if so=='popular' %}selected{% endif %}>빈도순</option>
                <option value="unpopular" {% if so=='unpopular' %}selected{% endif %}>작은순</option>
            {% endif %}
        </select>
    </div>
    <div class="col-4 input-group" style="max-width:500px;">
        <input type="text" class="form-control kw" value="{{ keyword or '' }}">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
        </div>
    </div>
</div>
<form id="searchForm" method="get">
    <input type="hidden" id="kw" name="kw" value="{{ keyword or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
<script type='text/javascript'>
$(document).ready(function(){
    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>